# v${version}
Debug: false

LockSymbol: "lock" # 普通锁
LockPasswordSymbol: "pwd" # 密码锁
LockFeeSymbol: "fee" # 付费锁
LockTokenSymbol: "token" # 代币锁

ShareSymbol: "#" # 添加共享
ManagerSymbol: "$" # 添加管理共享
RemoveSymbol: "-" # 除名
