name: RelateLock
version: '${project.version}'
main: io.fireflyest.relatelock.RelateLock
description: 牌子锁
api-version: '1.18'
authors: [Fireflyest]
softdepend: [Vault]

commands:
  lock:
    description: 主指令
    usage: /lock